#!/bin/bash
# Syntax: maildir2epub path/to/file.epub path/to/maildir
# Environment variables:
#
#       FILTER     Filter mail (e.g., "cat" to disable) 
#                  Default: unspeakable-filter
# 
#

epub=$1
maildir=$2

if [[ $# < 2 ]]; then
    cat $0 | sed -n '2,/^[^#]/p' | sed -n 's/^# //p'
    exit 1
fi
set ${FILTER:="unspeakable-filter"}

make_title() {
    perl -ne '
        if(/^Subject: (.*)/i) { $s = $1 };
        if(/^From: (\S+)/i) { $f = $1 };
        END {
            @w = ( $s =~ /(\S+)/g );
            $s = join(" ", @w[0..4])."-" if @w > 5;

            $title = "From $f about $s\n";

            $title =~ s/\s+/_/g;
            $title =~ s/[^\w\d ]//g;

            print $title;
        };' $1
}

if [ -d "$maildir/cur" ]; then
    maildir="$maildir/cur"
fi

tmp=$(mktemp --tmpdir=$TMPDIR -d maildir2epub.XXXXXX)
trap "[ -d $tmp ] && rm -rf $tmp" INT TERM EXIT

if [ -z "$FILTER" ]; then
    FILTER=cat
fi

seq=1
for f in $(ls -rt $maildir/*); do
    basename=$(basename $f)

    textmail $f | $FILTER > $tmp/$basename

    dest=$tmp/$((seq++))
    mkdir $dest

    mv $tmp/$basename "$dest/$(make_title $tmp/$basename).txt"
done

email_count=$(echo $maildir/* | wc -w)
title="$email_count emails from $(date "+%Y-%m-%d")"

echo "Saving '$title' as $epub"

emails=$(cd $tmp; ls */* | sort -n | sed "s|^|$tmp/|g")

txt2epub --title="$title" --creator="$(whoami)" --keep-line-breaks $epub $emails
